### ISSUE TITLE
but await().catch(e => errorHandling) already exists

### ISSUE THREAD

**Issue by shermango** [khanghoang/await-on#1]
title says it all, jk love you bro -- excited to see what this is :)

**Comment by khanghoang** [comment]
IMHO this is sexier
```
const [result, error] = await on(promise);
```

:-)

**Comment by shermango** [comment]
dude @coleturner beat you to it :O 

https://github.com/coleturner/promise.flatten

**Comment by coleturner** [comment]
Ha I wish I could take credit but I found it via a Medium article and later learned it’s already published at ‘await-to-js’. I only kept mine in case someone thinks “flatten”

**Comment by shermango** [comment]
lol OSS ftw
